theme = "lynx"
title = "Log'arithmÃ©"
copyright = "Â© 2024 Log'arithmÃ©"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "~Log'arithmÃ©~"
  headline = "â€¢ ğŸ® / ğŸ¦€ / ğŸ / ğŸ•¸ï¸ Developer â€¢ Playing with LLMs & Stable Diffusion"
  image = "author.jpg"
  links = [
	# { link = { href = "https://link-to-some-website.com/", text = "" } },
	{ itch = { href = "https://sairon711.itch.io/",	text = "itch.io" } },
    { github = "https://github.com/figo711" },
	{ linkedin = "https://www.linkedin.com/in/maxim-panis/" },
	{ discord = "https://discordapp.com/users/457850341149376513" },
	{ x = { href = "https://x.com/sairon711", text = "X (Twitter)" } },
	# { patreon = "https://www.patreon.com/username" },
	# { tumblr = "https://username.tumblr.com" },
	# { youtube = { href = "https://youtube.com/username", text = "" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
